# Root configuration file
# Defines FS wide options

# the FUSE filesystem name (defaults to scriptfs)
name = "Custom name"

# the mount point, relative to the parent of the template directory
# TODO: can be overriden from the executable
mount = "mnt"